### ISSUE TITLE
This is piracy and should be removed.

### ISSUE THREAD

**Issue by differentsmoke** [KevinOfNeu/tech-books-en#2]

**Comment by Holdge** [comment]
@differentsmoke I bought those books and knowledge should be FREE!

**Comment by differentsmoke** [comment]
I agree, but knowledge should also be sustainable.

Buying the books does not grant you redistribution rights. It still illegal.

**Comment by Holdge** [comment]
@differentsmoke When I bought those books, the book store granted to share books, If that is illegal, then the original sin is the books store...
