### ISSUE TITLE
Wanna Books

### ISSUE THREAD

**Issue by sixcold** [KevinOfNeu/tech-books-en#3]
1. build_your_own_website_the_right_way_using_html_css_3rd_edition.pdf
2. build_your_own_web_site_2nd_edition.pdf
3. creating_a_website_the_missing_manual_3rd_edition.pdf
4. python_3_web_development.pdf
5. python_web_development_with_django.pdf
6. learning_python_5th_edition.pdf 

my email: sixcolds@gmail.com

thank you :-)

**Comment by Holdge** [comment]
@lanpong email sent.
